import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Button from "../components/Button";
import IssueCard from "../components/IssueCard";
import Layout from "../components/Layout";
import {
  CommitObj1,
  CommitObj2,
  CommitObj3,
  CommitObj4,
} from "../components/smallerComponents/headerObjects";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>gitwin - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="overflow-hidden">
          <header className="px-36 flex flex-col justify-center h-[90vh] w-[100vw] overflow-hidden relative">
            <h1 className="font-extrabold text-7xl w-5/6 backdrop-blur-sm bg-white/50 ">
              Break free from your 9–5 to work on{" "}
              <span className="text-medium_sea_green ">open source</span>{" "}
              projects that matter.
            </h1>
            <h3 className="font-medium text-2xl text-dim_gray mt-4 mb-8 w-4/6 backdrop-blur-sm bg-white/50 ">
              Millions of dollars flow into projects on gitwin. Earn by
              participating in sponsored hackathons, bounties, and funded
              community grants.
            </h3>
            <Button type="black" className="">
              I’m ready to earn
            </Button>
            <CommitObj1 />
            <CommitObj2 />
            <CommitObj3 />
            <CommitObj4 />
          </header>
          <div className="flex gap-2 h-[90vh]">
            <section className="w-1/4 bg-black"></section>
            <section className="w-3/4 pl-10">
              <div className="mb-10">
                <h3 className="text-3xl font-extrabold">
                  Issue Explorer - Freelance Code Bounties
                </h3>
                <p className="font-medium text-xl text-dim_gray">
                  Choose a issue and start earning
                </p>
              </div>
              <div className="overflow-y-auto h-full pb-36 flex flex-col items-center">
                <div className="flex flex-col gap-4 mb-4 w-full pr-10">
                  <IssueCard />
                  <IssueCard />
                  <IssueCard />
                  <IssueCard />
                  <IssueCard />
                  <IssueCard />
                  <IssueCard />
                </div>
                <Button className="">
                    See more
                </Button>
              </div>
            </section>
          </div>
        </div>
      </Layout>
    </div>
  );
};

export default Home;
