import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Issue: NextPage = () => {
  return (
    <div>
      <Head>
        <title>gitwin - issue</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Issue;
